### ISSUE TITLE
Add comment field for user objects

### ISSUE THREAD

**Issue by HomeSen** [janstarke/ntdsextract2#1]
More often than not, administrators leave useful (and sometimes confidential) information inside user object comments. Thus, it would be nice to pull that information out of the NTDS.dit, too.

Thank you :)

**Comment by janstarke** [comment]
I'm using `ATTm131153` for user comments, but I'm not sure if this is correct. Do you have testdata with which you (or me) can verify this?

**Comment by HomeSen** [comment]
Thanks for looking into this. The `ntds.dit` is from a training, so it shouldn't contain any sensitive data ;)
[ntds.zip](https://github.com/janstarke/ntdsextract2/files/9083925/ntds.zip)

As can be seen in the `enum4linux-ng` output, there should be several comments:
![image](https://user-images.githubusercontent.com/663748/178263729-b06f9366-1a65-4c78-9803-e3acc8caccf2.png)
