### ISSUE TITLE
Support for password extraction

### ISSUE THREAD

**Issue by TheraNinjaCat** [janstarke/ntdsextract2#15]
The dsusers.py script in the original ntdsxtract supports extracting user password hashes with the following flags:

```
--syshive --lmoutfile --ntoutfile --pwformat --passwordhashes --passwordhistory
```

As the old tool is no longer seeing updates (and I'm having issues with the data output being incorrect) I was wondering if there are any plans to add this password extraction functionality to this tool.

**Comment by janstarke** [comment]
I do not plan to implement this functionality, as the tool `secretsdump` from impacket (https://github.com/fortra/impacket) has this functionality and is actively maintained. I suggest that you use this tool.

One other reason is that implementing such functionality is illegal in germany, which would render downloading `ntdsextract2` illegal as well, if you are in germany 🤦‍♂️

**Comment by TheraNinjaCat** [comment]
Understood, I've used `secretsdump` before, but found there's sometimes differences between the output between it and `ntdsxtract`, so there being two tools to essentially check their homework was useful, but I can use just `secretsdump` going forward.

I'm slightly shocked that implementing such functionality is illegal in Germany, as there are perfectly valid reasons to use such a tool, I'm curious to know what the specific stipulations are.
