### ISSUE TITLE
Invalid JSON output

### ISSUE THREAD

**Issue by TheraNinjaCat** [janstarke/ntdsextract2#18]
The output for the `-F json` is unreadable by another json parser, as rather than being one complete json object, it's just a series of new line separated json objects.

I believe this would be more useful if it were to output it as a list of json objects instead. This would still retain the human readability of the output, while enabling simpler parsing of the data in code.

A workaround is to use `-F json-lines` and then parse each line as its own object, however this feels less clean than just parsing the entire file at once.

**Comment by janstarke** [comment]
I agree with your argument and modified `ntdsextract2` to print a single JSON list instead of distinct JSON objects if you pass `--format json`.
