### ISSUE TITLE
more informative handling of special datetime values (such as 0)

### ISSUE THREAD

**Issue by janstarke** [janstarke/ntdsextract2#24]
> On the topic of odd output, I think this might need to be it's own separate issue, but I've got a large number of identical `account_expires` values that don't make sense, namely `01-01-1601T00:00:00+0000` and `14-09-+30828T02:48:05+0000`, while the former seems to potentially be the result of parsing a zero-value, I don't know what to make of the latter.

_Originally posted by @TheraNinjaCat in https://github.com/janstarke/ntdsextract2/issues/22#issuecomment-2313746034_

**Comment by janstarke** [comment]
Possible lower and upper bounds of datetime values are

- January 1, 1601 -- 30828-09-13T17:57:29+00:00 (<https://learn.microsoft.com/de-de/windows/win32/api/minwinbase/ns-minwinbase-filetime>)
- January 1, 1970 -- 2038-01-19T03:14:08 (<https://en.wikipedia.org/wiki/Unix_time>)

(<https://www.forensicfocus.com/articles/interpretation-of-ntfs-timestamps/>)

All those values could be handled as `None`, otherwise we could introduce a value similar to `NaN`: `NaT`

**Comment by TheraNinjaCat** [comment]
I guess it depends on how Windows itself interprets those two extremes, as it may use the earliest possible timestamp as a generic “expired” flag with regards to the expires_at value, and then the latest possible timestamp to mark it as “never expires”, and setting them both to the same “null” value is potentially removing relevant information for accounts.

**Comment by janstarke** [comment]
Correct. One other problem could be how to parse the json output. `null` with be simple, but all text entries who do not match a specific timestamp format would be problematic to parse

**Comment by janstarke** [comment]
We could to the following:

- text/csv output: handle upper/lower bound values as `None`
- json: the same, but for any timestamp `timestamp` we could optionally add a field `timestamp_raw_value` of JSON-type `Number`, which contains the originally stored value, to be interpreted by the user

I did a little research and found that Windows does not specify how those special values are to be interpreted. It is up to the application which uses the datatype. So there is nothing official what we can rely on

**Comment by TheraNinjaCat** [comment]
I just did a cursory glance, I'll check out the other attributes now, but it seems like my guess was close, but not entirely accurate. https://learn.microsoft.com/en-us/windows/win32/adschema/a-accountexpires in here they specify that values of `0` and `0x7FFFFFFFFFFFFFFF` _both_ mean that the account is set to never expire. As such for these values `null` would make sense for both.

**Comment by TheraNinjaCat** [comment]
These are my findings:

record_time: I couldn't figure which item in the AD schema this was
when_created: nothing specific
when_changed: nothing specific
last_logon: `0` means last logon time is unknown
last_logon_time_stamp: nothing specific but likely related to above
account_expires: both `0` and `0x7FFFFFFFFFFFFFFF` mean account does not expire
password_last_set: if `0` and UAC attr does not contain `"UF_DONT_EXPIRE_PASSWD"` then user must change password at next logon
bad_pwd_time: `0` means that the last time an incorrect password was used is unknown

I'm starting to err on the side of "this isn't the job of this tool to interpret", however this issue may help others in parsing the data.

**Comment by janstarke** [comment]
Sure, this could be extremely helpful. I'm currently struggling with two questions:

- How should this be displayed to the user in a way that can also parsed by a script?
- I currently have no internal distinction between, say, `account_expires` and `password_last_set`. Both have the same datatype and thus the same behavior and look&feel. How can I add some specific interpretation routine which is independent of the datatype? That should be no special code for only those attributes, but should be designed to be usable for potentially all attributes

The first question is more complicated, I think

**Comment by TheraNinjaCat** [comment]
When I am suggesting "this isn't the job of this tool to interpret", what I mean is that it's potentially best for ntdsextract2 itself to output it exactly as it already does, the timestamp as was extracted from the AD file, as the tool is called ntdsextract not ntdsinterpret, and these data values are just timestamps.

Instead, I think it might just call for some documentation in the README on how to interpret special timestamps, i.e. `0` (`01-01-1601T00:00:00+0000`) or `0x7FFFFFFFFFFFFFFF` (`14-09-+30828T02:48:05+0000`).

**Comment by janstarke** [comment]
I see, I misunderstood your suggestion. Having it in the documentation is indeed a very good idea :+1:
