### ISSUE TITLE
Feature request: display DN

### ISSUE THREAD

**Issue by janstarke** [janstarke/ntdsextract2#4]
the RDN attribute ID is stored in the `RDNTyp_col` column (<https://web.archive.org/web/20130401164208/http://blogs.chrisse.se/2012/02/15/how-the-active-directory-data-store-really-works-inside-ntds-dit-part-2/>)

**Comment by TheraNinjaCat** [comment]
Hi, just bumping this for any progress? It would be very useful to have the full distinguished name, just to resolve the situation where two users in two different domains have the same username.
